// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

public partial class TaskList
{
    [Key]
    public int TaskListId { get; set; }

    public int TaskCategoryId { get; set; }

    public DateTime CreateDate { get; set; }

    public int TaskModeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Title { get; set; }

    public bool IsDeleted { get; set; }

    [Required]
    public bool? Active { get; set; }

    [ForeignKey("TaskCategoryId")]
    [InverseProperty("TaskList")]
    public virtual TaskCategory TaskCategory { get; set; }

    [ForeignKey("TaskModeId")]
    [InverseProperty("TaskList")]
    public virtual TaskMode TaskMode { get; set; }
}