// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

public partial class TaskMode
{
    [Key]
    public int TaskModeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Title { get; set; }

    public bool IsDeleted { get; set; }

    public bool Active { get; set; }

    [InverseProperty("TaskMode")]
    public virtual ICollection<TaskList> TaskList { get; } = new List<TaskList>();
}