// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

public partial class TaskCategory
{
    [Key]
    public int TaskCategortId { get; set; }

    [Required]
    [StringLength(10)]
    public string CategoryName { get; set; }

    public bool IsDeleted { get; set; }

    [Required]
    public bool? Active { get; set; }

    [InverseProperty("TaskCategory")]
    public virtual ICollection<TaskList> TaskList { get; } = new List<TaskList>();
}